services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Services de scan avec le tag explicite
    App\Service\Scanner\SemgrepScanner:
        tags: ['app.scanner']

    App\Service\Scanner\EslintScanner:
        tags: ['app.scanner']

    App\Service\Scanner\NpmAuditScanner:
        tags: ['app.scanner']

    App\Service\Scanner\TruffleHogScanner:
        tags: ['app.scanner']

    App\Service\ScanOrchestrator:
        arguments:
            $scanners: !tagged_iterator app.scanner
