services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\Scanner\:
        resource: '../src/Service/Scanner/'
        tags: ['app.scanner']

    App\Service\ScanOrchestrator:
        arguments:
            $scanners: !tagged_iterator app.scanner