security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        options:
            pattern: ^/
            methods: [OPTIONS]
            security: false

        login:
            pattern: ^/api/auth/login$
            stateless: true
            json_login:
                check_path: /api/auth/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                username_path: email
                password_path: password

        register:
            pattern: ^/api/auth/register$
            security: false

        github:
            pattern: ^/api/auth/github
            security: false

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/auth/login,           roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/register,        roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/github,          roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/github/callback, roles: PUBLIC_ACCESS }
        - { path: ^/api,                      roles: IS_AUTHENTICATED_FULLY }