<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260303095800 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE fix (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, original_code TEXT NOT NULL, fixed_code TEXT NOT NULL, explanation TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, vulnerability_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_59FA476072897D8B ON fix (vulnerability_id)');
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, git_url VARCHAR(500) NOT NULL, language VARCHAR(100) DEFAULT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE scan_result (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tool VARCHAR(100) NOT NULL, raw_json JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CFDBE4ED166D1F9C ON scan_result (project_id)');
        $this->addSql('CREATE TABLE vulnerability (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file VARCHAR(500) DEFAULT NULL, line INT DEFAULT NULL, description TEXT NOT NULL, severity VARCHAR(50) NOT NULL, owasp_category VARCHAR(10) DEFAULT NULL, tool VARCHAR(100) DEFAULT NULL, fix_status VARCHAR(50) NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6C4E4047166D1F9C ON vulnerability (project_id)');
        $this->addSql('ALTER TABLE fix ADD CONSTRAINT FK_59FA476072897D8B FOREIGN KEY (vulnerability_id) REFERENCES vulnerability (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE scan_result ADD CONSTRAINT FK_CFDBE4ED166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vulnerability ADD CONSTRAINT FK_6C4E4047166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA pgbouncer');
        $this->addSql('CREATE SCHEMA realtime');
        $this->addSql('CREATE SCHEMA extensions');
        $this->addSql('CREATE SCHEMA vault');
        $this->addSql('CREATE SCHEMA graphql_public');
        $this->addSql('CREATE SCHEMA graphql');
        $this->addSql('CREATE SCHEMA auth');
        $this->addSql('CREATE SCHEMA storage');
        $this->addSql('ALTER TABLE fix DROP CONSTRAINT FK_59FA476072897D8B');
        $this->addSql('ALTER TABLE scan_result DROP CONSTRAINT FK_CFDBE4ED166D1F9C');
        $this->addSql('ALTER TABLE vulnerability DROP CONSTRAINT FK_6C4E4047166D1F9C');
        $this->addSql('DROP TABLE fix');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE scan_result');
        $this->addSql('DROP TABLE vulnerability');
    }
}
